# Generated by Django 5.1.3 on 2024-11-22 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_associate_certifications_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="associates",
        ),
        migrations.AddField(
            model_name="associate",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="associates",
                to="tracker.team",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceevent",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="updated_attendance_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="alerted_users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="%(class)s_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="witnessed_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="%(class)s_witnessed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryaction",
            name="alerted_users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="%(class)s_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryaction",
            name="witnessed_by",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="%(class)s_witnessed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
