# Generated by Django 5.1.3 on 2024-11-22 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_shifttime_end_time_alter_shifttime_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="associate",
            name="shift_time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_time",
                to="tracker.shifttime",
            ),
        ),
    ]
